---
name: mcaf-mcvs-docker-action
description: mcaf-mcvs-docker-action
inputs:
  token:
    description: |
      A token is required to allow the mcaf-mcvs-docker-action to push the
      image that it has been built, to the packages repository of the GitHub
      repository where the action has been run.
    required: true
runs:
  using: "composite"
  steps:
    - uses: hadolint/hadolint-action@v1.6.0
      with:
        dockerfile: Dockerfile
    - name: Log in to the Container registry
      uses: docker/login-action@v3.0.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.token }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5.0.0
      with:
        images: ghcr.io/${{ github.repository }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v5.1.0
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
